import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Smooch } from "next/font/google";
import { Gwendolyn } from "next/font/google";
import { Poppins } from "next/font/google";
import { Press_Start_2P } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const smooch = Smooch({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-smooch",
});
const gwendolyn = Gwendolyn({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-gwendolyn",
});
const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-poppins",
});
const pressStart2P = Press_Start_2P({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-pressStart",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} ${smooch.variable} ${gwendolyn.variable} ${poppins.variable} ${pressStart2P.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
