import { StructurePage } from "@/components/common/StructurePage";
import "./globals.css";
import type { Metadata } from "next";
import {
  Inter,
  Smooch,
  Gwendolyn,
  Poppins,
  Press_Start_2P,
} from "next/font/google";
import { NavBar } from "@/components/common/NavBar";
import { PageTitle } from "@/components/common/PageTitle";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const smooch = Smooch({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-smooch",
});
const gwendolyn = Gwendolyn({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-gwendolyn",
});
const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-poppins",
});
const pressStart2P = Press_Start_2P({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-pressStart2P",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} ${smooch.variable} ${gwendolyn.variable} ${poppins.variable} ${pressStart2P.variable} `}
      >
        <StructurePage>
          <PageTitle />
          <NavBar />
          {children}
        </StructurePage>
      </body>
    </html>
  );
}
